# Generated by Django 3.1.3 on 2020-11-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parazite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contaminationMethod', models.CharField(max_length=255)),
                ('symptoms', models.CharField(max_length=255)),
                ('protection', models.CharField(max_length=255)),
                ('distribution', models.FloatField()),
            ],
        ),
    ]
